ps-AlgorithmStudy/Algorithm_JAVA

- junho/src/week4/Main_bj_골드5_5639_이진검색트리.java
- 백준_골드5_5639_이진검색트리 풀이(완)
1. 트리 구성 (배열 인덱싱)
2. 왼쪽 서브트리, 오른쪽 서브트리, 루트 탐색 수행(재귀)
> week4 : 풀이 (1/3)

- junho/src/week7/Main_bj_1238_파티.java
- junho/src/week7/Main_bj_1918_후위표기식.java
- junho/src/week7/Main_bj_4386_별자리만들기.java
https://www.acmicpc.net/problem/1238
i.  X-> {모든 정점} 에 대한 최단 거리(비용) 구하기
ii. {모든 정점} -> X 에 대한 최단 거리(비용) 구하면서 max 갱신해주기
```java
static void solution() {
int[] dist1 = new int[N + 1];
dijkstra(dist1);
// 중간 정답 기록
int[] answer = Arrays.copyOf(dist1, N + 1);
int max = 0;
for (int s = 1; s <= N; s++) {
int cost = dijkstra(s);
max = Math.max(max, cost + answer[s]);
}
System.out.println(max);
}
static void dijkstra(int[] dist) {
boolean[] v = new boolean[N + 1];
Arrays.fill(dist, INF);
//int min = 0, stopOver = 0;
dist[X] = 0;
for(int i = 1; i <= N; i++) {
// step1) 미방문 영역 중 출발지에서 가장 가중치가 작은 정점을 경유지로 선택
// stopOver = -1;
int minVertex = -1;
int min = INF;
for (int j = 1; j <= N; j++) {
if (!v[j] && min > dist[j]) {
minVertex = j;
min = dist[j];
}
}
if (minVertex == -1) break;
// step2) 방문 처리 …
```
> week7: MST 유형 풀이

- hanseul/src/dp/week8_bj_1932_정수삼각형.java
week 8 REVIEW
- 백준 1629 곱셈
- https://www.acmicpc.net/problem/1629
문제 설명 : a, b, c를 입력받고 (a ^ b) % c 를 구하는 문제
1 try )
단순히 a 를 b 번 곱하는 연산을 하면서 c 모듈연산을 수행함
-> 결과 : 시간 초과
2 try )
A^10 = A^5 * A^5 임을 사용하여
A^5를 한번만 구해서 두번 곱하면 된다
그러면 log2(b)로 문제를 해결할 수 있다.
--------------------------------------------------------------------------------------
- 백준 14676 영우는 사기꾼
- https://www.acmicpc.net/problem/14676
선이수과목과 같은 구조이기 때문에 위상정렬 사용했음.
<저장한 데이터>
build 배열에 그래프의 간선을 저장함
한 빌딩을 세우기 위해서 필요한 조건 빌딩들의 개수를 indegrees에 저장함.
mode == 1 // 빌딩 건설
// 빌딩을 건설하기 위한 조건이 충족되었는지 확인
checkBuild라는 HashSet자료구조를 사용했음.
1 ) 빌딩을 건설할 때 건설해야할 a 빌딩이 나중에 건설할지도 모르는 b 빌딩에 영향을 준다면 checkBuild에 add 함
2 ) 빌딩을 건설할 때마다 curbuildings 배열에 빌딩의 개수를 ++ 해주면서 카운트 해줌.
즉, checkBuild 의 개수와 입력하면서 계산해둔 indegrees 의 수를 비교하여 빌딩건설 유무를 체크함
만약 건설 빌딩이 불가능하다면 Lier …
> #PR 8 week 김한슬 코드 리뷰

- junho/src/week11/Main_bj_2805_나무자르기.java
- junho/src/week11/P_사라지는발판.java
- junho/src/week11/Solution_prg_입국심사.java
- 재귀를 이용한 완전 탐색
- 기저 조건의 순서가 중요
- 입력의 크기가 커지면 효율적인 풀이 필요
**게임 규칙**
- N x M 공간
- 좌상단(0,0) 우하단(N-1, M-1)
- 플레이어 A, B는 게임이 끝날 때까지 양 플레이어가 몇 번 움직이게 될지 예측
- 각 플레이어는 1 x 1 공간의 발판에서 시작
- 발판이 있는 곳으로만 이동
- 발판은 이동하고 나서는 사라짐
- 보드 밖 이동 불가능
- 각 플레이어는 번갈아가며 자신의 캐릭터를 상-하-좌-우로 인접한 4개의 칸 중 발판이 있는 칸으로 옮김
**게임 진행 관련**
- A 플레이어가 먼저 진행
- 각 플레이어는 최적의 플레이 수행
- 이길 수 있는 플레이어는 최대한 빨리 승리하도록 플레이
- 질 수 밖에 없는 플레이어는 최대한 오래 버티도록 플레이
- 자신이 움직일 차례인데 4방향에 모두 발판이 없다 && 보드 밖 범위라 이동 불가능하다. → 해당 차례 플레이어의 패배
- 두 캐릭터가 같은 발판에 있을 때 먼저 이동 가능한 플레이어는 승리, 남아있는 플레이어는 패배
이기는 쪽은 → 게임 이동 횟수를 최소화하여 승리한다.
지는 쪽은 → 게임 턴수를 최대화 하고 패배한다.
```
어떤 p가 승리 가능하다면 
- 최소 이동 횟수를 갱신하고 그 결과를 반환한다.
어떤 p가 패배한다면
- 최대 이동 횟수를 갱신하고 그 결과를 반환한다.
```
⇒ **최종적으로 이렇게 플레이를 누적했을 때의 결과를 반환한다.**
- N, M in [1, 5]
- board의 원소는 0 : 발판 없음, 1 : 발판 있음
- aloc → 플레이어 A (r, c)의 1차원 …
> # Week 11, 사라지는 발판, 입국심사

- hanseul/src/Dijkstra/week12_pg_2022Kakao_등산코스정하기.java
- hanseul/src/graph/week12_bj_9466_텀프로젝트.java
-------------------------
https://school.programmers.co.kr/learn/courses/30/lessons/118669
문제 설명 :
gate 와 summit 이 주어지며
등산 코스 조건은
gate1 -> summit -> gate1 을 충족시켜야함.
이때 gate는 시작점과 종점이 같은 gate 여야한다.
등산코스 중 weight 가 최대인 가중치를 intensity 라고 지정한다.
여러개의 등산 코스 중 intensity 가 최소인 값을 찾아내야함!
문제 풀이 :
gate 와 summit 를 구분할 수 있는 boolean 배열에 정보를 담아 
O(1) 로 gate 와 summit 를 구분할 수 있음.
prim 알고리즘을 사용함.
등산 코스 조건 : gate1 -> summit -> gate1 를 다시 해석하면
gate1 -> summit 이 가능하다면 summit->gate1 도 충족됨.
각 gate 별로 weight 가 최소인 경로를 우선으로 intensity를 계산 후,
intensity 중 최소값을 리턴한다.
--------------------------
https://www.acmicpc.net/problem/9466
문제 설명 :
각 학생이 원하는 팀원이 각 한명씩 존재한다. 
이때 모든 학생들은 프로젝트를 함께 하고 싶은 학생을 선택해야 하고,
팀에 속하지 못한 학생의 수를 출력해야 한다.!
문제 풀이 :
싸이클에 속하는 학생과 속하지 못한 학생을 구분해야한다.
이때 한번 검사한 학생에 대해서는 검사하지 않기 위해 v[] 배열을 사용하여
방문을 …
> PR- 1102/Hanseul

- junho/src/week12/Solution_P_등산코스정하기.java
---
```java
// n in [2, 5만]
// gates in [1, n]
// summits in [1,n]
// 출입구이면서 동시에 산봉우린 X
```
---
- 외판원 순회?
- 재귀, 백트랙킹?
→  N in [2, 5만] 너무 큼
- 서로 다른 두 지점을 직접 연결하는 등산로는 최대 1개
- 임의의 두 지점 사이에 이동 가능한 경로가 항상 존재
⇒ MST? 
⇒ 그런데 싸이클 이 있네
- 최단 거리(비용) 구하는 알고리즘
- 각 경로에 대해 최장 비용을 갱신하는데 그러한 경로 중 최소를 찾는 알고리즘 구현?
→ 그런데 시작점이 여러개일 수 있다!
1. graph를 구성한다
```java
// graph를 구성
List<Node>[] graph;
static class Node implements Comparable<Node> {
int key;
int cost;
Node(int key, int cost) {
this.key = key; 
this.cost = cost;
}
@Override
public String toString() {
return "Node{key: "+key+", cost: "+ cost+"}";
}
@Override
public int compareTo(Node n){
return Integer.compare(this.cost, n.cost); // 오름차순
}
}
// ... 
initGraph(n, paths);
```
1. 방문 정점의 유형을 O(1)로 확인하기 위한 Set 타입 객체들 생성
```java
Set<Integer> summitSet; …
```
> Week12 : 프로그래머스-등산코스정하기 / 백준 텀프로젝트

- hanseul/src/graph/week13_bj_16724_피리부는사나이.java
- hanseul/src/graph/week13_pg_2023kakao_미로탈출명령어.java
링크 : [https://school.programmers.co.kr/learn/courses/30/lessons/150365]
[문제 설명]
k 횟수만큼 이동하여 시작지점에서 목표지점까지 가야한다.!
이때 가는 방향을 각
왼 : L / 오 : R / 상 : U / 하 : D 라고 정의할때
사전순으로 가장 빠른 경로를 구하시오.
만약 k 번으로 목적지까지 도착할 수 없을 때, impossible 리턴.
[문제 풀이]
1. dfs 탐색을 사용해야 함.
2. 사전 순이기 대문에 d l r u 순으로 탐색을 진행한다.
3. 먼저  depth : k 로 탐색이 가능하다면 모든 탐색을 종료한다.
** k 번으로 도착할 수 없을 때는 어떻게 판단해야 할까?
point A, point B 가 존재할 때 A -> B 로 가는 최소 경로를 d라고 했을 때,
조건 1 ) k 는 d 보다 크거나 같아야한다.
조건 2 ) 무조건 k번까지 이동해야하기 때문에 k - d 가 짝수여야한다.
_(d번 이동해서 B 에 도착한 이후 남은 횟수를 채우기 위해 이동한다고 했을때 최소 2번씩 이동해야 도착지에 최종적으로 남아있을 수 있기 때문 )_
링크 : [https://www.acmicpc.net/problem/16724]
[문제 설명]
지도에 움직일 수 있는 방향이 주어지고 
지도 위에서는 해당 타일의 방향대로 움직일 수 있다.
이때 지도 어느 구역에 있더라도 갈 수 있는 safe zone 의 최소 개수를 출력해야 함.
[문제 풀이]
1 Try) 문제 예시만 보고 cycle 의 개수를 출력하면 된다고 생각하여
dfs 를 사용해서 cycle …
> WEEK13 HANSEUL PR

- junho/src/week14/Main_bj_3089_FindClover.java
- 2차원 공간, 시작 위치는 (0, 0) 
- N : 클로버 개수 [3, 10만]
- 클로버 위치 (x, y) 좌표 in [-10만, 10만]
- M : 명령 수 [1, 10만]
- 한 방향에 정해지면 해당 방향에 하나의 클로버는 존재함!
- 첫번째 클로버를 만날때까지 이동
Q. 모든 명령이 수행되었을 때 최종 위치는?
1. naive하게 생각하기
- M 개의 명령을 수행하며 매번 좌표 공간 탐색해서 클로버 확인? O(ML) ; L : 최악의 경우 20만
=>  각 단계에서 이분 탐색으로 위치 찾기!
> 1130: BOJ_2089 외판원 순회 / BOJ_3089 네잎클로버를 찾아서

- hanseul/.idea/uiDesigner.xml
- hanseul/src/Dijkstra/week15_bj_네트워크복구.java
- hanseul/src/graph/week14_bj_2098_외판원순회.java
- hanseul/src/graph/week16_bj_12893_적의적.java
- hanseul/src/graph/week16_bj_1525_퍼즐.java
- hanseul/src/implementation/week10_pg_디스크컨트롤러.java
- hanseul/src/implementation/week14_bj_3089_네잎클로버를찾아서.java
[문제 접근]
1. 각 컴퓨터에 대해 최단경로로 연결되어있어야함.
2. 모든 컴퓨터가 연결되어있어야함.
3. (회선을 쳐냈을 때보다 오래 걸리는 링크는 없어야함.)
[문제 해설]
MST 문제임은 단번에 알았지만 3번 조건이 이 문제의 핵심이라고 생각
1. 이전보다 더 오래걸리는 링크를 없애기 위해 다익스트라를 사용.
2. path 배열에 minVertex 값을 갖게 한 edge Num을 저장함.
3. 중복되는 결과값을 저장하기 위해 HashSet 을 사용함.
[아쉬운 점]
문제해설 3번에서 중복을 제거하기 위해 <String> 을 사용하여 단순 비교를 했지만 int[]와 같이 start, end 만 저장하고 comparator 을 사용했다면
- 결과 String 을 만드는데 소요되는 시간
- 불필요한 저장공간
위와 같은 점들을 좀 더 개선할 수 있다고 생각함.
>  week 15 bj 네트워크복구

- hyeongjin/src/week14/Main_2098.java
- hyeongjin/src/week14/Main_BJ3089.java
- hyeongjin/src/week15/Main_2211.java
- hyeongjin/src/week16/Main_12893.java
- hyeongjin/src/week16/Main_1525.java
1. 최소 개수의 회선만을 복구한다.
2. 원래의 네트워크에서 통신하는 데 걸리는 최소 시간보다 커져서는 안된다.
- 기본적인 다익스트라를 통해 풀이
- 정점의 정보는 2차원 배열의 좌표에 비용을 넣어 기록
- 컴퓨터 번호와 거리를 배열로 기록
- 거리 배열은 최댓값으로 초기화
1.  방문 할 정점 중 최단 거리를 찾아 저장
2.  방문 처리 후 최단거리 갱신
3.  최단 경로 정보를 결과 리스트에 저장
```
// line:49
if(!visited[j] && dist[j] > minVal + map[minIdx][j]){
...
```
처음에 INF에 `Integer.MAX_VALUE`를 넣어줬는데 원하는 결과값이 나오지 않았다
저기서 오버플로우가 났을 것으로 예상돼서 INF를 1,000,000,000 정도로 하니 해결
무지성 Integer.MAX_VALUE 사용보단 적당히 큰 값을 찾아내 보아야겠다...
> week15 : BOJ 2211 : 네트워크 복구

- byeongchang/src/week16/bj_12893_적의_적.java
- byeongchang/src/week16/bj_1525_퍼즐.java
- byeongchang/src/week17/Solution_bj_2533_사회망_서비스.java
[https://www.acmicpc.net/problem/1525](https://www.acmicpc.net/problem/1525)
- 최소 이동으로 초기 상태 만들기
- Slide Puzzle Algorithm(풀 수 없는 퍼즐 확인, 링크 참고)
- - [https://www.cs.princeton.edu/courses/archive/spring21/cos226/assignments/8puzzle/specification.php](https://www.cs.princeton.edu/courses/archive/spring21/cos226/assignments/8puzzle/specification.php)
- - [https://natejin.tistory.com/m/22](https://natejin.tistory.com/m/22)
- bfs
- 주어진 2차원 배열을 1차원 문자열로 변환해서 계산
- bfs를 통한 완전 탐색
- hashmap을 이용한 방문처리
[https://www.acmicpc.net/problem/12893](https://www.acmicpc.net/problem/12893)
- 적의 적은 친구이다
- dfs
- dfs와 비슷하게 재귀를 수행하면서 팀을 저장하는 배열을 채움
- 배열이 이미 채워져 있다면 팀 번호를 비교해 같으면 명제 증명 실패, 다르면 넘어감
> bj 1525 퍼즐, bj 12893 적의 적

- junho/src/week17/Main_bj_9252_LCS2.java
- 첫째 줄, 둘째 줄에 두 문자열 주어짐
- 문자열은 알파벳 대문자로만 이루어짐
- 최대 1000글자 구성
LCS 길이와 LCS 문자열을 출력한다.
- 메모리 초과
> 트리 DP는 한번도 안 풀어봐서... 설명 듣는걸루
> LCS2, 사회망 서비스(SNS)

- byeongchang/src/week18/bj_1277_발전소_설치.java
- byeongchang/src/week18/pg_176962_과제_진행하기.java
[https://www.acmicpc.net/problem/1277](https://www.acmicpc.net/problem/1277)
- 필요한 추가 전선 길이 최소값
- 현재 남아있는 전선이 있음
- 전선 연결할 때 길이가 M을 초과하면 안됨
- 다익스트라
- 우선순위 큐
- 우선순위 큐를 사용하기 위해 Node 클래스를 만듬(발전소 번호는 int이고, 사용한 전선 길이는 double이라 배열보다 클래스를 사용하는 것이 편했음)
- N이 최대 1000이라서 이차원 배열 만들어도 4MB이므로, 이차원 배열을 이용해서 전선이 남아있는 발전소 표시(1 : 연결되어 있음, 0: 연결되어 있지 않음)
- 다익스트라를 1부터 각 발전소까지 필요한 최소 전선 길이를 갱신하는 방식으로 사용
- 이미 연결되어 있는 발전소의 경우 현재 발전소에서 다음 발전소를 연결하는데 추가적인 전선은 필요 없음
- 방문처리 안하면 메모리 초과 날 수도 있음(우선순위 큐가 무한하게 증가하는 듯??)
[https://school.programmers.co.kr/learn/courses/30/lessons/176962](https://school.programmers.co.kr/learn/courses/30/lessons/176962)
- 새로운 과제를 시작할 시간일 때, 진행 중인 과제는 멈추고 새로운 과제를 시작함
- 과제를 끝냈을 때, 다음 과제 시작 시간과 차이가 있다면 멈춘 과제를 수행해야 함
- 멈춘 과제가 여러 개면 최근에 중단한 과제부터 수행해야 함
- 우선순위 큐( 다음 과제 확인용)
- 스택(멈춘 과제 확인용)
- …
> bj 1277 발전소 설치, pg 176962 과제 진행하기

- hanseul/.idea/misc.xml
- hanseul/src/dp/week20_pg_2024kakao_산모양타일링.java
[문제 설명]
-----
길이가 1인 삼각형을 기준으로 삼각형으로 이루어진 사다리꼴을 만들것이다.
n 은 사다리꼴 윗변의 길이이다. 
tops 는 사다리꼴 윗변과 변을 공유하는 삼각형의 존재유무를 나타낸 배열이다.
[문제 풀이]
-----
n 이 주어질때 아래 사다리꼴을 구성하는 삼각형의 개수는 2 * n +  1 이다.
dp 를 사용하여 문제를 풀이했다.
사다리꼴 기준으로 삼각형이 
**1개 있을 때** 경우의 수는 `1`
**2개 있을 때** 경우의 수는 `2`이다. (만약 2번째 삼각형 위에 삼각형이 붙어있다면 경우의 수는 `3`이다.)
=> dp[0] = 1 / dp[1] = 2 || 3
이후 dp를 사용하여 식을 계산한다.
점화식은 `dp[i] = dp[i - 1] + dp[i - 2]` 이다.
* dp[i - 1] : 삼각형 타일을 추가할 경우
* dp[i - 2] : (이전 삼각형과 이어진) 마름모 타일을 추가할 경우
이때, 만약 홀수 번째 삼각형에서 tops 배열에 의해 위에 추가된 삼각형이 있다고 판단되었을 때,
점화식은 `dp[i] = dp[i] + dp[i - 1]` 이다.  (이때 dp[i] 는 첫번째 점화식의 결과값이다.)
* dp[i] :  삼각형 타일을 추가할 경우
* dp[i - 1] : (이전 삼각형과 이어진) 마름모 타일을 추가할 경우
이후 결과값은 dp 배열의 마지막으로 계산된 dp[2 * n] 값이다. 
+) 오버플로우를 방지하기 위해 %10007을 점화식 계산과 함께 해줘야한다.
> week20 pg 2024kakao 산모양타일링

- junho/src/week19/Prog_산모양타일링.java
- 점화식 세우고
- 이전 상태가 현재 가짓수에 영향을 주지 않는 경우와
- 이전 상태가 현재 가짓수에 영향을 주는 경우로 구분
그러면서 tops[i] 가 1이냐 0이냐에 따라 경우의 수를 추가하는 방식 고려
https://tech.kakao.com/2023/12/27/2024-coding-test-winter-internship/
https://jaimemin.tistory.com/2352
> week20: 프로그래머스_산모양타일링

- junho/src/week22/PRG_주사위고르기.java
> 2024 카카오 - 주사위 굴리기 수정본

- junho/src/week23/PRG_파괴되지않은건물.java
failed: 단순 구현 접근시
- N, M in [1, 1000] 조건과
- skills in [1, 25만] 조건
- 정확성 테스트용 입력이랑 문제 입력 범위가 달랐음
- N, M in [1, 100]
- skills in [1, 100]
**⇒ 효율성은 처음 주어진 문제 입력 범위로 진행한다!**
1. 단순 구현; 당연히 failed
2. 2차원 배열에서의 누적합
> 24-02-17 카카오 2022 - 파괴되지 않은 건물 풀이

- hanseul/src/Main.java
- hanseul/src/graph/week21_pg_도넛과막대그래프.java
[문제 설명]
도넛 그래프, 막대 그래프, 8자 그래프가 존재한다.
이 그래프들을 연결하는 생성점(정점)과 각 그래프 종류의 개수를 리턴해야 한다.
[문제 풀이]
(1) 생성점 : input ( 0 ) output ( n >= 2 )
(2) 막대그래프 : input ( ? ) output ( 0 )
(3) 도넛그래프 : 생성점의 output 개수 - ( (2) + (3))
(4) 8자 그래프  : input ( n >= 2 ) output ( 2 )
> 도넛과 막대그래프 풀이

- mingyun/project/src/week19/Main.java
- mingyun/project/src/week23/Solution.java
범위를 누적해서 나중에 한번에 업데이트하는 방식인 누적합을 사용
```
for (int[] s : skill) {
int type = s[0], r1 = s[1], c1 = s[2], r2 = s[3], c2 = s[4], degree = s[5];
if (type == 1) {
degree = -degree;
}
array[r1][c1] += degree;
array[r1][c2 + 1] -= degree;
array[r2 + 1][c1] -= degree;
array[r2 + 1][c2 + 1] += degree;
}
```
위와 같이 시작점과 끝점에 표시해주고 한칸 옆에 반대로 해서 표시함
이렇게 한뒤 
```
for (int i = 0; i < n; i++) {
for (int j = 1; j < m; j++) {
array[i][j] += array[i][j - 1];
}
}
for (int i = 1; i < n; i++) {
for (int j = 0; j < m; j++) {
array[i][j] += array[i - 1][j];
}
}
```
영향 범위에서 순회해서 더하면 알 수 있음!
> week23 : 파괴되지 않은 건물

- hyeongjin/src/마법사상어와토네이도.java
- 토네이도가 (N/2 , N/2)를 시작점으로 시계 반대방향으로 회전하며 퍼져나가며 이동
- 토네이도가 지나간 자리에 있던 모래는 토네이도 진행 방향에 따라 근처 위치로 일정량 이동
- 모래가 이동한 좌표가 범위 밖이면 밖으로 나간 것이라고 표현
- 이 때 나간 모래의 양은?
- 시계 방향으로 방향을 전환해 가며 이동
- 1칸 이동 -> (방향전환) -> 1칸이동 -> (방향전환, 거리+1) -> 2칸 이동 -> (방향전환) -> 2칸이동 -> (방향전환 , 거리+1)...
- 토네이도가 지나갈 위치의 모래를 따로 저장
- 각각 이동 위치에 모래 추가, 범위 밖일시 결과값에 추가
- 남은 모래를 alpha 위치에 추가
> 마법사상어와토네이도
